---
title: 탱커펀드 블로그
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ask@tanker.fund
description: '탱커펀드는 금융의 최고 전문가와 젊은 IT 전문인력이 만난 진정한 핀테크 플랫폼입니다.'
baseurl: ''
url: https://tankerfund.github.io/
twitter_username: jekyllrb
github_username: tankerfund
markdown: kramdown
